version: '3.9'
services:
  influxdb:
    image: influxdb:2
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "${INFLUXDB_PORT}:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMINNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMINPASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORGNAME}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKETNAME}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMINTOKEN}
    volumes:
      - influxdb-volume:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - INFLUXDB_USERNAME=${INFLUXDB_ADMINNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMINTOKEN}
      - INFLUXDB_DATABASE=${INFLUXDB_BUCKETNAME}
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
